### ISSUE TITLE
1.5.9 Android still fails with CMake

### ISSUE THREAD

**Issue by bonnmh** [lugg/react-native-config#848]
"react": "19.0.0",
    "react-native": "0.79.6",
    "expo": "53.0.17",
    "react-native-config": "1.5.9",

Android project still fails with CMake errors even after cleaning caches.
I already tried:

Deleted android/app/cxx and android/app/build directories

Rebuilt the project

But the error persists.
```
CMake Error at  android/app/build/generated/autolinking/src/main/jni/Android-autolinking.cmake:22 (add_subdirectory):
  add_subdirectory given source
  "/node_modules/react-native-config/android/build/generated/source/codegen/jni/"
  which is not an existing directory.
```

**Comment by procoder7** [comment]
Latest version "react-native-config": "1.5.9" build is breaking, "react-native-config": "1.5.5" is working fine for me, i am using react-native version 0.79.1

**Comment by akash78422** [comment]
> Use this version in my case, it works perfectly: "react-native-config": "^1.5.5" ✨🔧💯

can i know the version of react native you are using?

**Comment by trushal-dev1111** [comment]
> > Use this version in my case, it works perfectly: "react-native-config": "^1.5.5" ✨🔧💯
> 
> can i know the version of react native you are using?

I'm using react-native 0.78.0

**Comment by zahid502** [comment]
> // <----- RN Config

It's also worked for me by following @cl3i550n 

>  "react": "19.1.0",
   "react-native": "0.81.1",
   "react-native-config": "^1.5.9"

add ` add(RNCConfigPackage())` instead of ` packages.add(RNCConfigPackage())`

<img width="993" height="541" alt="Image" src="https://github.com/user-attachments/assets/159bf7a9-e19d-49d9-9100-7326767381dd" />

**Comment by huynextlevel** [comment]
> ```
> "react": "19.0.0",
> "react-native": "0.79.6",
> "expo": "53.0.17",
> "react-native-config": "1.5.9",
> ```
> 
> Android project still fails with CMake errors even after cleaning caches. I already tried:
> 
> Deleted android/app/cxx and android/app/build directories
> 
> Rebuilt the project
> 
> But the error persists.
> 
> ```
> CMake Error at  android/app/build/generated/autolinking/src/main/jni/Android-autolinking.cmake:22 (add_subdirectory):
>   add_subdirectory given source
>   "/node_modules/react-native-config/android/build/generated/source/codegen/jni/"
>   which is not an existing directory.
> ```

Me too

**Comment by TheLazyH** [comment]
[react-native-config-solution.md](https://github.com/user-attachments/files/22195383/react-native-config-solution.md)

**Comment by TheLazyH** [comment]
# React Native Config Integration with React Native 0.79+

```
apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"
```

---

## Issue

When integrating `react-native-config` with React Native 0.79+ (Kotlin + New Architecture), you may encounter:

```
Unresolved reference 'lugg'
Unresolved reference 'RNCConfigPackage'
```

This happens because:

- Android is unable to auto-link `react-native-config` due to the Gradle setup.  
- Old build artifacts in `android/app/build` and `android/app/cxx` conflict with the module. These directories contain CMake and JNI build outputs, and can cause Gradle to fail when stale files remain.  

---

## Why auto-link fails

Even though `RNCConfigPackage.java` exists under `node_modules/react-native-config/android`, Gradle cannot resolve it until the module is explicitly linked.  
If Android Studio shows the file but Kotlin cannot compile, it means Gradle has not added the module to the classpath.

You can confirm whether the project is linked correctly by checking this import in `MainApplication.kt`:

```kotlin
import com.lugg.RNCConfig.RNCConfigPackage
```

Using `cmd+click` (macOS) or `ctrl+click` (Windows) on `RNCConfigPackage` should navigate you to the correct file inside `node_modules`. If it does, linking is successful.

---

## Fix
### react-native.config 
```sh
module.exports = {
  project: {
    ios: {},
    android: {},
  },
 dependencies: {
    'react-native-config': { platforms: { android: null } },
  },
};
```
### 1. Clean old build files
```sh
rm -rf android/app/build android/app/cxx
cd android
./gradlew clean
cd ..
```

### 2. Configure `settings.gradle`
```gradle
include ':react-native-config'
project(':react-native-config').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-config/android')
```

### 3. Configure `app/build.gradle`
```gradle
project.ext.envConfigFiles = [
    debug: ".env.development",
    release: project.hasProperty('ENVFILE') ? project.property('ENVFILE') : ".env.production",
    staging: ".env.staging"
]

apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"

dependencies {
    implementation project(':react-native-config')
}
```

### 4. gradle.properties
```properties
newArchEnabled=true
ENVFILE=.env
```

### 5. MainApplication.kt
```kotlin
import com.lugg.RNCConfig.RNCConfigPackage // <-

override fun getPackages(): List<ReactPackage> =
    PackageList(this).packages.apply {
        add(RNCConfigPackage()) // <-
    }
```

### 6. Package.json scripts
```json
"scripts": {
  "android": "ENVFILE=.env.staging react-native run-android",
  "android:dev": "ENVFILE=.env.development react-native run-android",
  "android:prod": "ENVFILE=.env.production react-native run-android"
}
```

### 7. Env files
Place these in the project root:
```
.env
.env.development
.env.staging
.env.production
```

### 8. Accessing values in code
In `App.js`:
```js
import React from 'react';
import { Text, View } from 'react-native';
import Config from 'react-native-config';

export default function App() {
  return (
    <View>
      <Text>API URL: {Config.API_URL}</Text>
    </View>
  );
}
```

---

## Conclusion

- The issue is caused by missing Gradle linkage and stale CMake/JNI build files under `android/app/build` and `android/app/cxx`.  
- Proper Gradle configuration and cleaning the build output resolves the `Unresolved reference 'lugg'` error.  
- You can verify whether `react-native-config` is linked correctly by opening `MainApplication.kt` and checking this import:

```kotlin
import com.lugg.RNCConfig.RNCConfigPackage

In Android Studio, hold cmd+click (macOS) or ctrl+click (Windows/Linux) on RNCConfigPackage.
If the linking is correct, it should navigate you directly to the class inside node_modules/react-native-config/android.

**Comment by RN-Akash** [comment]
> > Use this version in my case, it works perfectly: "react-native-config": "^1.5.5" ✨🔧💯
> 
> can i know the version of react native you are using?

react native version. 0.78.0

**Comment by Zunaira-Haroon** [comment]
I'm facing the same issue. Even i manually link it.

"react-native": "0.81.1", 
"react-native-config": "^1.5.9",

Error:
 Task :app:configureCMakeDebug[arm64-v8a] FAILED
C/C++: CMake Error at /Users/official/app/android/app/build/generated/autolinking/src/main/jni/Android-autolinking.cmake:16

This issue raise when i install the package 

Anyone have solution?

**Comment by cl3i550n** [comment]
> I'm facing the same issue. Even i manually link it.
> 
> "react-native": "0.81.1", 
> "react-native-config": "^1.5.9",
> 
> Error:
>  Task :app:configureCMakeDebug[arm64-v8a] FAILED
> C/C++: CMake Error at /Users/official/app/android/app/build/generated/autolinking/src/main/jni/Android-autolinking.cmake:16
> 
> This issue raise when i install the package 
> 
> Anyone have solution?

Read the previous messages

**Comment by Zunaira-Haroon** [comment]
I tried all of the above solutions but none of them worked for me.
What finally solved my issue was editing node_modules/react-native-config/package.json and adding:

"codegenConfig": null

If there’s already an object under codegenConfig, just replace it with null.
After this change, my Android build succeeded.

**Comment by hamzadar2013** [comment]
@Zunaira-Haroon what is your react native and config version mine is 0.80.2 i have tried to upgrade my RN project from 0.68 to 0.80 react native config is failing all the time

**Comment by Yurii-Lutsyk** [comment]
I've also faced this issue with "react-native": "0.81.4". Looking forward to the fix in the next version

**Comment by hardik-pelago** [comment]
Facing same issue for "react-native": "0.81.4" @luancurti can you please check we are facing issues due to this

**Comment by trushal-dev1111** [comment]
Inside react-native.config.js, 
just add:
dependencies: {
  'react-native-config': {
    platforms: { android: null },
  },
},

And that’s it 🎉 — works perfectly for me ! 🚀
My friend was facing the same issue, and this fix solved it for them as well ✨🙌

**Comment by cl3i550n** [comment]
> ### Workaround: Disable autolinking for `react-native-config` and link manually
> 
> ### My Environment:
> RN: 0.81.0
> RN-Config: 1.5.7
> NDK: 27.1.12297006
> Gradle: 8.14.3
> MacOS: Sequoia 15.6.1 M2
> CMake (Android SDK): 3.22.1
> 
> If you want to avoid editing `node_modules`, you can disable autolinking for `react-native-config` and add it manually in your Gradle setup.
> 
> **1. Add or edit `react-native.config.js` at the root of your project:**
> ```js
> module.exports = {
>   dependencies: {
>     'react-native-config': { platforms: { android: null } },
>   },
> };
> ```
> 
> **2. Add or edit `android/settings.gradle`:**
> ```js
> include ':react-native-config'
> project(':react-native-config').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-config/android')
> ```
> 
> **3. Add or edit `android/app/build.gradle`:**
> ```js
> apply ....
> apply ....
> 
> apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle" // <---- add this in top
> 
> react {
> ...
> }
> 
> dependencies {
>     implementation ...
>     implementation ....
> 
>     implementation project(':react-native-config') // <---- add this
> 
> ...
> }
> ```
> 
> **4. Add or edit `src/main/java/MainApplication.kt`:**
> ```js
> import com.lugg.RNCConfig.RNCConfigPackage // <--- Add this import
> 
> // Replace getPackages to use `RNCConfigPackage`
> 
> override val reactNativeHost: ReactNativeHost =
>     object : DefaultReactNativeHost(this) {
> 
>       override fun getPackages(): List<ReactPackage> {
>         val packages = PackageList(this).packages.toMutableList()
>         packages.add(RNCConfigPackage()) // <----- RN Config
>         return packages
>       }
> 
>       override fun getJSMainModuleName(): String = "index"
>       override fun getUseDeveloperSupport(): Boolean = BuildConfig.DEBUG
>       override val isNewArchEnabled: Boolean = BuildConfig.IS_NEW_ARCHITECTURE_ENABLED
>       override val isHermesEnabled: Boolean = BuildConfig.IS_HERMES_ENABLED
>     }
> ```
> 
> This way, React Native won’t try to run codegen/autolinking for react-native-config (which causes the CMake error), and the module will still be available in your Android build.

Try it guys, check all steps

**Comment by nakshatrasinghh** [comment]
Hi everyone,

I’m currently working on configuring product flavors for my Android project and could use some community insight. I’m aiming to set up multiple flavors (e.g., dev, staging, prod — or white-label variants) with different:

- Application IDs
- API endpoints
- App names/icons
- Build configurations & dependencies

I’ve read the official docs and have a basic setup, but I’m running into issues around this CMake thing! [This](https://github.com/lugg/react-native-config/issues/847#issuecomment-3248950469) helped but my build.gradle does not look good!

Could anyone who’s successfully implemented complex product flavors share:

1. Their `build.gradle` (app-level) structure?
2. Tips for organizing flavor-specific resources and code?
3. Common pitfalls to avoid?

Any sample repos, snippets, or advice would be hugely appreciated 🙏

Thanks in advance for your help!

**Comment by hamzadar2013** [comment]
@nakshatrasinghh 

**in app/build.gradle place this code *

- Top of the file paste blew code till apply from 

project.ext {
    envConfigFiles = [
        developmentDebug: ".env.development",
        developmentRelease: ".env.development",
        stagingDebug: ".env.staging",
        stagingRelease: ".env.staging",
        productionDebug: ".env.production",
        productionRelease: ".env.production"
    ]
}
apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"

- Paste below code inside android block

productFlavors {
    production {
        dimension 'default'
        applicationId "com.example.myapp"
        resValue "string", "app_name", "MyApp - Prod"
    }
    staging {
        dimension 'default'
        applicationId "com.example.myapp.staging"
        resValue "string", "app_name", "MyApp - Staging"
    }
    development {
        dimension 'default'
        applicationId "com.example.myapp.dev"
        resValue "string", "app_name", "MyApp - Dev"
    }
    uat {
        dimension 'default'
        applicationId "com.example.myapp.uat"
        resValue "string", "app_name", "MyApp - UAT"
    }
}


in your AndroidManifest.xml

android:label="@string/app_name"

**Comment by hamzadar2013** [comment]
@nakshatrasinghh add below script in your package.json
    "android:staging": "react-native run-android --mode=stagingDebug",
    "android:staging-release": "react-native run-android --mode=stagingRelease",
    "android:dev": "react-native run-android --mode=developmentDebug",
    "android:dev-release": "react-native run-android --mode=developmentRelease",
    "android:prod": "react-native run-android --mode=productionDebug",
    "android:prod-release": "react-native run-android --mode=productionRelease",

and in terminal run yarn android:staging or yarn android:staging-release

**Comment by hamzadar2013** [comment]
@nakshatrasinghh what IDE are you using you can tell curser to debug and resolve the issue

**Comment by bmatasar** [comment]
Actually, it does not work.
The main problem is that the Spec defines the method
```
  get(key: string): string;
```
In the JNI generated class, it will be generated as
```
   virtual jsi::String get(jsi::Runtime &rt, jsi::String key) = 0;
```
which conflicts with the virtual method `get` of `TurboModule`
```
   jsi::Value get(jsi::Runtime& runtime, const jsi::PropNameID& propName)
```

Log of the error is
```
  In file included from ~/AwesomeProject/node_modules/react-native-config/android/build/generated/source/codegen/jni/react/renderer/components/RNCConfigModule/RNCConfigModuleJSI-generated.cpp:10:
  ~/AwesomeProject/node_modules/react-native-config/android/build/generated/source/codegen/jni/react/renderer/components/RNCConfigModule/RNCConfigModuleJSI.h:24:23: error: 'facebook::react::NativeRNCConfigCxxSpecJSI::get' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
     24 |   virtual jsi::String get(jsi::Runtime &rt, jsi::String key) = 0;
        |                       ^
  ~/.gradle/caches/8.14.3/transforms/5e3de19cdc6bd36e24739a92b8cabbb2/transformed/react-android-0.81.4-debug/prefab/modules/reactnative/include/ReactCommon/TurboModule.h:58:14: note: hidden overloaded virtual function 'facebook::react::TurboModule::get' declared here: type mismatch at 2nd parameter ('const jsi::PropNameID &' vs 'jsi::String')
     58 |   jsi::Value get(jsi::Runtime& runtime, const jsi::PropNameID& propName)
        |              ^
  1 error generated.
```
It looks like without renaming the get method, it is not going to work

**Comment by kilinccagatay** [comment]
following

**Comment by overpassconnect** [comment]
react-native-config 1.5.5 works with react-native 0.79.2 and JDK 20 on macOS (Apple Sillicon)

**Comment by EmilJunker** [comment]
Is anybody actually going to fix this?! The latest React Native release 0.82 and all future releases support only the new architecture. For months, react-native-config has been broken when used with the new architecture. Are we supposed to rely on the autolinking workaround forever? Or is there an actual fix in sight?
